name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
      
      - name: Test
        run: npm run lint

      - name: Bump Version & Git Tag
        if: github.ref == 'refs/heads/main'
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
          commit-message: '[skip ci] bumps version to {{version}}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
